# Makefile - mdlviewer.dsw

.PHONY: all
all: \
	mdlviewer

.PHONY: mdlviewer
mdlviewer:
	$(MAKE) -f mdlviewer.mak

.PHONY: clean
clean:
	$(MAKE) -f mdlviewer.mak clean

.PHONY: depends
depends:
	$(MAKE) -f mdlviewer.mak depends

